---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: swiggy
spec:
  containers:
    - name: cont-1
      image: httpd
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
