---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      app: swiggy
  template:
      metadata:
        labels:
          app: swiggy
      spec:
        containers:
          - name: cont-1
            image: nginx
            ports:
              - containerPort: 80
